// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file mtm/sppb/ag.proto (package sppb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { TeamGetReply, TeamGetRequest } from "./ag_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sppb.AgService
 */
export const AgService = {
  typeName: "sppb.AgService",
  methods: {
    /**
     * @generated from rpc sppb.AgService.TeamGet
     */
    teamGet: {
      name: "TeamGet",
      I: TeamGetRequest,
      O: TeamGetReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

