// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file mtm/sppb/ag.proto (package mtmai.pb, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mtm/sppb/ag.proto.
 */
export const file_mtm_sppb_ag: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChFtdG0vc3BwYi9hZy5wcm90bxIIbXRtYWkucGIiNAoOVGVhbUdldFJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEg8KB3RlYW1faWQYAiABKAkiHwoMVGVhbUdldFJlcGx5Eg8KB3RlYW1faWQYASABKAkiIgoSRGVtb1N0cmVhbTFSZXF1ZXN0EgwKBG5hbWUYASABKAkiIAoQRGVtb1N0cmVhbTFSZXBseRIMCgRuYW1lGAEgASgJIhwKDEdyZWV0UmVxdWVzdBIMCgRuYW1lGAEgASgJIiEKDUdyZWV0UmVzcG9uc2USEAoIZ3JlZXRpbmcYASABKAkyxwEKCUFnU2VydmljZRI9CgdUZWFtR2V0EhgubXRtYWkucGIuVGVhbUdldFJlcXVlc3QaFi5tdG1haS5wYi5UZWFtR2V0UmVwbHkiABI8CgVHcmVldBIWLm10bWFpLnBiLkdyZWV0UmVxdWVzdBoXLm10bWFpLnBiLkdyZWV0UmVzcG9uc2UiACgBEj0KBkdyZWV0MhIWLm10bWFpLnBiLkdyZWV0UmVxdWVzdBoXLm10bWFpLnBiLkdyZWV0UmVzcG9uc2UiADABQoEBCgxjb20ubXRtYWkucGJCB0FnUHJvdG9QAVonZ2l0aHViLmNvbS9jb2RlaDAwNy9nb210bS9tdG0vc3BwYjtzcHBiogIDTVBYqgIITXRtYWkuUGLKAghNdG1haVxQYuICFE10bWFpXFBiXEdQQk1ldGFkYXRh6gIJTXRtYWk6OlBiYgZwcm90bzM",
    [file_google_protobuf_descriptor],
  );

/**
 * @generated from message mtmai.pb.TeamGetRequest
 */
export type TeamGetRequest = Message<"mtmai.pb.TeamGetRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string team_id = 2;
   */
  teamId: string;
};

/**
 * Describes the message mtmai.pb.TeamGetRequest.
 * Use `create(TeamGetRequestSchema)` to create a new message.
 */
export const TeamGetRequestSchema: GenMessage<TeamGetRequest> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 0);

/**
 * @generated from message mtmai.pb.TeamGetReply
 */
export type TeamGetReply = Message<"mtmai.pb.TeamGetReply"> & {
  /**
   * @generated from field: string team_id = 1;
   */
  teamId: string;
};

/**
 * Describes the message mtmai.pb.TeamGetReply.
 * Use `create(TeamGetReplySchema)` to create a new message.
 */
export const TeamGetReplySchema: GenMessage<TeamGetReply> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 1);

/**
 * @generated from message mtmai.pb.DemoStream1Request
 */
export type DemoStream1Request = Message<"mtmai.pb.DemoStream1Request"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message mtmai.pb.DemoStream1Request.
 * Use `create(DemoStream1RequestSchema)` to create a new message.
 */
export const DemoStream1RequestSchema: GenMessage<DemoStream1Request> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 2);

/**
 * @generated from message mtmai.pb.DemoStream1Reply
 */
export type DemoStream1Reply = Message<"mtmai.pb.DemoStream1Reply"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message mtmai.pb.DemoStream1Reply.
 * Use `create(DemoStream1ReplySchema)` to create a new message.
 */
export const DemoStream1ReplySchema: GenMessage<DemoStream1Reply> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 3);

/**
 * @generated from message mtmai.pb.GreetRequest
 */
export type GreetRequest = Message<"mtmai.pb.GreetRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message mtmai.pb.GreetRequest.
 * Use `create(GreetRequestSchema)` to create a new message.
 */
export const GreetRequestSchema: GenMessage<GreetRequest> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 4);

/**
 * @generated from message mtmai.pb.GreetResponse
 */
export type GreetResponse = Message<"mtmai.pb.GreetResponse"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message mtmai.pb.GreetResponse.
 * Use `create(GreetResponseSchema)` to create a new message.
 */
export const GreetResponseSchema: GenMessage<GreetResponse> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 5);

/**
 * @generated from service mtmai.pb.AgService
 */
export const AgService: GenService<{
  /**
   * @generated from rpc mtmai.pb.AgService.TeamGet
   */
  teamGet: {
    methodKind: "unary";
    input: typeof TeamGetRequestSchema;
    output: typeof TeamGetReplySchema;
  };
  /**
   * demos
   *
   * @generated from rpc mtmai.pb.AgService.Greet
   */
  greet: {
    methodKind: "client_streaming";
    input: typeof GreetRequestSchema;
    output: typeof GreetResponseSchema;
  };
  /**
   * @generated from rpc mtmai.pb.AgService.Greet2
   */
  greet2: {
    methodKind: "server_streaming";
    input: typeof GreetRequestSchema;
    output: typeof GreetResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_mtm_sppb_ag, 0);
