// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file mtm/sppb/ag.proto (package mtmai.mtm.sppb, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Paging } from "./mtm_pb";
import { file_mtm_sppb_mtm } from "./mtm_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mtm/sppb/ag.proto.
 */
export const file_mtm_sppb_ag: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChFtdG0vc3BwYi9hZy5wcm90bxIObXRtYWkubXRtLnNwcGIiIgoSRGVtb1N0cmVhbTFSZXF1ZXN0EgwKBG5hbWUYASABKAkiIAoQRGVtb1N0cmVhbTFSZXBseRIMCgRuYW1lGAEgASgJIhwKDEdyZWV0UmVxdWVzdBIMCgRuYW1lGAEgASgJIiEKDUdyZWV0UmVzcG9uc2USEAoIZ3JlZXRpbmcYASABKAkiawoNQWdlbnRSdW5JbnB1dBIRCgl0ZW5hbnRfaWQYASABKAkSDgoGcnVuX2lkGAIgASgJEg8KB2NvbnRlbnQYAyABKAkSEwoLcnVuX3N0ZXBfaWQYBCABKAkSEQoJc2Vzc2lvbklkGAUgASgJIjoKD0dldENvbXBvbmVudFJlcRIRCgl0ZW5hbnRfaWQYASABKAkSFAoMY29tcG9uZW50X2lkGAMgASgJIj4KEENvbXBvbmVudExpc3RSZXESKgoKUGFnaW5hdGlvbhgBIAEoCzIWLm10bWFpLm10bS5zcHBiLlBhZ2luZyI0CglDb21wb25lbnQSFAoMY29tcG9uZW50X2lkGAEgASgJEhEKCWNvbXBvbmVudBgCIAEoDCJ3ChBDb21wb25lbnRMaXN0UmVzEioKClBhZ2luYXRpb24YASABKAsyFi5tdG1haS5tdG0uc3BwYi5QYWdpbmcSKAoFaXRlbXMYAiADKAsyGS5tdG1haS5tdG0uc3BwYi5Db21wb25lbnQSDQoFVG90YWwYAyABKAUyxQIKCUFnU2VydmljZRJICgVHcmVldBIcLm10bWFpLm10bS5zcHBiLkdyZWV0UmVxdWVzdBodLm10bWFpLm10bS5zcHBiLkdyZWV0UmVzcG9uc2UiACgBEkkKBkdyZWV0MhIcLm10bWFpLm10bS5zcHBiLkdyZWV0UmVxdWVzdBodLm10bWFpLm10bS5zcHBiLkdyZWV0UmVzcG9uc2UiADABElUKDUNvbXBvbmVudExpc3QSIC5tdG1haS5tdG0uc3BwYi5Db21wb25lbnRMaXN0UmVxGiAubXRtYWkubXRtLnNwcGIuQ29tcG9uZW50TGlzdFJlcyIAEkwKDEdldENvbXBvbmVudBIfLm10bWFpLm10bS5zcHBiLkdldENvbXBvbmVudFJlcRoZLm10bWFpLm10bS5zcHBiLkNvbXBvbmVudCIAQqABChJjb20ubXRtYWkubXRtLnNwcGJCB0FnUHJvdG9QAVonZ2l0aHViLmNvbS9jb2RlaDAwNy9nb210bS9tdG0vc3BwYjtzcHBiogIDTU1TqgIOTXRtYWkuTXRtLlNwcGLKAg5NdG1haVxNdG1cU3BwYuICGk10bWFpXE10bVxTcHBiXEdQQk1ldGFkYXRh6gIQTXRtYWk6Ok10bTo6U3BwYmIGcHJvdG8z",
    [file_google_protobuf_descriptor, file_mtm_sppb_mtm],
  );

/**
 * @generated from message mtmai.mtm.sppb.DemoStream1Request
 */
export type DemoStream1Request =
  Message<"mtmai.mtm.sppb.DemoStream1Request"> & {
    /**
     * @generated from field: string name = 1;
     */
    name: string;
  };

/**
 * Describes the message mtmai.mtm.sppb.DemoStream1Request.
 * Use `create(DemoStream1RequestSchema)` to create a new message.
 */
export const DemoStream1RequestSchema: GenMessage<DemoStream1Request> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 0);

/**
 * @generated from message mtmai.mtm.sppb.DemoStream1Reply
 */
export type DemoStream1Reply = Message<"mtmai.mtm.sppb.DemoStream1Reply"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message mtmai.mtm.sppb.DemoStream1Reply.
 * Use `create(DemoStream1ReplySchema)` to create a new message.
 */
export const DemoStream1ReplySchema: GenMessage<DemoStream1Reply> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 1);

/**
 * @generated from message mtmai.mtm.sppb.GreetRequest
 */
export type GreetRequest = Message<"mtmai.mtm.sppb.GreetRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message mtmai.mtm.sppb.GreetRequest.
 * Use `create(GreetRequestSchema)` to create a new message.
 */
export const GreetRequestSchema: GenMessage<GreetRequest> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 2);

/**
 * @generated from message mtmai.mtm.sppb.GreetResponse
 */
export type GreetResponse = Message<"mtmai.mtm.sppb.GreetResponse"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message mtmai.mtm.sppb.GreetResponse.
 * Use `create(GreetResponseSchema)` to create a new message.
 */
export const GreetResponseSchema: GenMessage<GreetResponse> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 3);

/**
 * @generated from message mtmai.mtm.sppb.AgentRunInput
 */
export type AgentRunInput = Message<"mtmai.mtm.sppb.AgentRunInput"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string run_id = 2;
   */
  runId: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: string run_step_id = 4;
   */
  runStepId: string;

  /**
   * @generated from field: string sessionId = 5;
   */
  sessionId: string;
};

/**
 * Describes the message mtmai.mtm.sppb.AgentRunInput.
 * Use `create(AgentRunInputSchema)` to create a new message.
 */
export const AgentRunInputSchema: GenMessage<AgentRunInput> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 4);

/**
 * @generated from message mtmai.mtm.sppb.GetComponentReq
 */
export type GetComponentReq = Message<"mtmai.mtm.sppb.GetComponentReq"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string component_id = 3;
   */
  componentId: string;
};

/**
 * Describes the message mtmai.mtm.sppb.GetComponentReq.
 * Use `create(GetComponentReqSchema)` to create a new message.
 */
export const GetComponentReqSchema: GenMessage<GetComponentReq> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 5);

/**
 * @generated from message mtmai.mtm.sppb.ComponentListReq
 */
export type ComponentListReq = Message<"mtmai.mtm.sppb.ComponentListReq"> & {
  /**
   * @generated from field: mtmai.mtm.sppb.Paging Pagination = 1;
   */
  Pagination?: Paging;
};

/**
 * Describes the message mtmai.mtm.sppb.ComponentListReq.
 * Use `create(ComponentListReqSchema)` to create a new message.
 */
export const ComponentListReqSchema: GenMessage<ComponentListReq> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 6);

/**
 * @generated from message mtmai.mtm.sppb.Component
 */
export type Component = Message<"mtmai.mtm.sppb.Component"> & {
  /**
   * @generated from field: string component_id = 1;
   */
  componentId: string;

  /**
   * @generated from field: bytes component = 2;
   */
  component: Uint8Array;
};

/**
 * Describes the message mtmai.mtm.sppb.Component.
 * Use `create(ComponentSchema)` to create a new message.
 */
export const ComponentSchema: GenMessage<Component> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 7);

/**
 * @generated from message mtmai.mtm.sppb.ComponentListRes
 */
export type ComponentListRes = Message<"mtmai.mtm.sppb.ComponentListRes"> & {
  /**
   * @generated from field: mtmai.mtm.sppb.Paging Pagination = 1;
   */
  Pagination?: Paging;

  /**
   * @generated from field: repeated mtmai.mtm.sppb.Component items = 2;
   */
  items: Component[];

  /**
   * @generated from field: int32 Total = 3;
   */
  Total: number;
};

/**
 * Describes the message mtmai.mtm.sppb.ComponentListRes.
 * Use `create(ComponentListResSchema)` to create a new message.
 */
export const ComponentListResSchema: GenMessage<ComponentListRes> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_ag, 8);

/**
 * @generated from service mtmai.mtm.sppb.AgService
 */
export const AgService: GenService<{
  /**
   * demos
   *
   * @generated from rpc mtmai.mtm.sppb.AgService.Greet
   */
  greet: {
    methodKind: "client_streaming";
    input: typeof GreetRequestSchema;
    output: typeof GreetResponseSchema;
  };
  /**
   * @generated from rpc mtmai.mtm.sppb.AgService.Greet2
   */
  greet2: {
    methodKind: "server_streaming";
    input: typeof GreetRequestSchema;
    output: typeof GreetResponseSchema;
  };
  /**
   * component
   *
   * @generated from rpc mtmai.mtm.sppb.AgService.ComponentList
   */
  componentList: {
    methodKind: "unary";
    input: typeof ComponentListReqSchema;
    output: typeof ComponentListResSchema;
  };
  /**
   * @generated from rpc mtmai.mtm.sppb.AgService.GetComponent
   */
  getComponent: {
    methodKind: "unary";
    input: typeof GetComponentReqSchema;
    output: typeof ComponentSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_mtm_sppb_ag, 0);
