// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=none"
// @generated from file mtm/sppb/agent.proto (package sppb, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import {
  file_google_protobuf_any,
  file_google_protobuf_descriptor,
  file_google_protobuf_field_mask,
  file_google_protobuf_timestamp,
} from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mtm/sppb/agent.proto.
 */
export const file_mtm_sppb_agent: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChRtdG0vc3BwYi9hZ2VudC5wcm90bxIEc3BwYiJ5CgtSdW5BZ2VudFJlcRIMCgRuYW1lGAEgASgJEi0KBnBhcmFtcxgDIAMoCzIdLnNwcGIuUnVuQWdlbnRSZXEuUGFyYW1zRW50cnkaLQoLUGFyYW1zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASIkCg1SdW5BZ2VudFJlcGx5EhMKC21lc3NhZ2VfY2huGAEgASgJMkQKDEFnZW50U2VydmljZRI0CghSdW5BZ2VudBIRLnNwcGIuUnVuQWdlbnRSZXEaEy5zcHBiLlJ1bkFnZW50UmVwbHkiAEJqCghjb20uc3BwYkIKQWdlbnRQcm90b1ABWiJnaXRodWIuY29tL2NvZGVoMDA3L2dvbXRtL210bS9zcHBiogIDU1hYqgIEU3BwYsoCBFNwcGLiAhBTcHBiXEdQQk1ldGFkYXRh6gIEU3BwYmIGcHJvdG8z",
    [
      file_google_protobuf_any,
      file_google_protobuf_timestamp,
      file_google_protobuf_descriptor,
      file_google_protobuf_field_mask,
      file_buf_validate_validate,
    ],
  );

/**
 * @generated from message sppb.RunAgentReq
 */
export type RunAgentReq = Message<"sppb.RunAgentReq"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: map<string, string> params = 3;
   */
  params: { [key: string]: string };
};

/**
 * Describes the message sppb.RunAgentReq.
 * Use `create(RunAgentReqSchema)` to create a new message.
 */
export const RunAgentReqSchema: GenMessage<RunAgentReq> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_agent, 0);

/**
 * @generated from message sppb.RunAgentReply
 */
export type RunAgentReply = Message<"sppb.RunAgentReply"> & {
  /**
   * 运行成功告诉调用者从什么地方拉取消息
   *
   * @generated from field: string message_chn = 1;
   */
  messageChn: string;
};

/**
 * Describes the message sppb.RunAgentReply.
 * Use `create(RunAgentReplySchema)` to create a new message.
 */
export const RunAgentReplySchema: GenMessage<RunAgentReply> =
  /*@__PURE__*/
  messageDesc(file_mtm_sppb_agent, 1);

/**
 * @generated from service sppb.AgentService
 */
export const AgentService: GenService<{
  /**
   * @generated from rpc sppb.AgentService.RunAgent
   */
  runAgent: {
    methodKind: "unary";
    input: typeof RunAgentReqSchema;
    output: typeof RunAgentReplySchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_mtm_sppb_agent, 0);
