// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file mtm/sppb/agent.proto (package sppb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RunAgentReply, RunAgentReq } from "./agent_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sppb.AgentService
 */
export const AgentService = {
  typeName: "sppb.AgentService",
  methods: {
    /**
     * @generated from rpc sppb.AgentService.RunAgent
     */
    runAgent: {
      name: "RunAgent",
      I: RunAgentReq,
      O: RunAgentReply,
      kind: MethodKind.Unary,
    },
  },
} as const;
