// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts,import_extension=none,ts_nocheck=true"
// @generated from file mtm/sppb/agent.proto (package sppb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AgentService } from "./agent_pb";

/**
 * @generated from rpc sppb.AgentService.RunAgent
 */
export const runAgent = AgentService.method.runAgent;
