// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts,import_extension=none,ts_nocheck=true"
// @generated from file mtm/sppb/mtm.proto (package sppb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MtmService } from "./mtm_pb";

/**
 * @generated from rpc sppb.MtmService.Oauth2LoginHook
 */
export const oauth2LoginHook = MtmService.method.oauth2LoginHook;

/**
 * @generated from rpc sppb.MtmService.Login
 */
export const login = MtmService.method.login;

/**
 * @generated from rpc sppb.MtmService.Register
 */
export const register = MtmService.method.register;

/**
 * gomtm 基本元数据
 *
 * @generated from rpc sppb.MtmService.GetMeta
 */
export const getMeta = MtmService.method.getMeta;

/**
 * @generated from rpc sppb.MtmService.PullLogs
 */
export const pullLogs = MtmService.method.pullLogs;

/**
 * 获取可用服务器列表
 *
 * @generated from rpc sppb.MtmService.MtmServerList
 */
export const mtmServerList = MtmService.method.mtmServerList;

/**
 * @generated from rpc sppb.MtmService.ServiceMeta
 */
export const serviceMeta = MtmService.method.serviceMeta;

/**
 * 统一的列表查询接口
 *
 * @generated from rpc sppb.MtmService.Search
 */
export const search = MtmService.method.search;

/**
 * 动态页面
 *
 * @generated from rpc sppb.MtmService.SlugPage
 */
export const slugPage = MtmService.method.slugPage;

/**
 * 因为涉及到用户会话状态，所以用户登录上下文菜单独立定制
 *
 * @generated from rpc sppb.MtmService.Userinfo
 */
export const userinfo = MtmService.method.userinfo;

/**
 * blog-post
 *
 * @generated from rpc sppb.MtmService.BlogPostList
 */
export const blogPostList = MtmService.method.blogPostList;

/**
 * @generated from rpc sppb.MtmService.BlogPostGet
 */
export const blogPostGet = MtmService.method.blogPostGet;

/**
 * @generated from rpc sppb.MtmService.BlogPostCreate
 */
export const blogPostCreate = MtmService.method.blogPostCreate;

/**
 * @generated from rpc sppb.MtmService.BlogPostUpdate
 */
export const blogPostUpdate = MtmService.method.blogPostUpdate;

/**
 * @generated from rpc sppb.MtmService.BlogPostDelete
 */
export const blogPostDelete = MtmService.method.blogPostDelete;

/**
 * @generated from rpc sppb.MtmService.BlogPostImport
 */
export const blogPostImport = MtmService.method.blogPostImport;

/**
 * blog-categorie
 *
 * @generated from rpc sppb.MtmService.BlogCategorieList
 */
export const blogCategorieList = MtmService.method.blogCategorieList;

/**
 * @generated from rpc sppb.MtmService.BlogCategorieGet
 */
export const blogCategorieGet = MtmService.method.blogCategorieGet;

/**
 * @generated from rpc sppb.MtmService.BlogCategorieCreate
 */
export const blogCategorieCreate = MtmService.method.blogCategorieCreate;

/**
 * @generated from rpc sppb.MtmService.BlogCategorieUpdate
 */
export const blogCategorieUpdate = MtmService.method.blogCategorieUpdate;

/**
 * @generated from rpc sppb.MtmService.BlogCategorieDelete
 */
export const blogCategorieDelete = MtmService.method.blogCategorieDelete;

/**
 * 清理重复内容
 *
 * @generated from rpc sppb.MtmService.BlogClean
 */
export const blogClean = MtmService.method.blogClean;

/**
 * Site
 *
 * @generated from rpc sppb.MtmService.SiteList
 */
export const siteList = MtmService.method.siteList;

/**
 * @generated from rpc sppb.MtmService.SiteGet
 */
export const siteGet = MtmService.method.siteGet;

/**
 * @generated from rpc sppb.MtmService.SiteCreate
 */
export const siteCreate = MtmService.method.siteCreate;

/**
 * @generated from rpc sppb.MtmService.SiteUpdate
 */
export const siteUpdate = MtmService.method.siteUpdate;

/**
 * @generated from rpc sppb.MtmService.SiteDelete
 */
export const siteDelete = MtmService.method.siteDelete;

/**
 * 灵活创建spSite
 * 站点（自动提取目标域名，自动创建相关配置，确保导入后能立即生效）
 *
 * @generated from rpc sppb.MtmService.SiteImport
 */
export const siteImport = MtmService.method.siteImport;

/**
 * @generated from rpc sppb.MtmService.SiteSetupCftunnel
 */
export const siteSetupCftunnel = MtmService.method.siteSetupCftunnel;

/**
 * 站点域名配置
 *
 * @generated from rpc sppb.MtmService.SiteHostList
 */
export const siteHostList = MtmService.method.siteHostList;

/**
 * @generated from rpc sppb.MtmService.SiteHostGet
 */
export const siteHostGet = MtmService.method.siteHostGet;

/**
 * @generated from rpc sppb.MtmService.SiteHostCreate
 */
export const siteHostCreate = MtmService.method.siteHostCreate;

/**
 * @generated from rpc sppb.MtmService.SiteHostUpdate
 */
export const siteHostUpdate = MtmService.method.siteHostUpdate;

/**
 * @generated from rpc sppb.MtmService.SiteHostDelete
 */
export const siteHostDelete = MtmService.method.siteHostDelete;

/**
 * @generated from rpc sppb.MtmService.FormList
 */
export const formList = MtmService.method.formList;

/**
 * @generated from rpc sppb.MtmService.FormGet
 */
export const formGet = MtmService.method.formGet;

/**
 * @generated from rpc sppb.MtmService.FormCreate
 */
export const formCreate = MtmService.method.formCreate;

/**
 * 文本内容分类(过时，因为文章分类不会直接调用)
 *
 * @generated from rpc sppb.MtmService.ArtContentClassify
 */
export const artContentClassify = MtmService.method.artContentClassify;

/**
 * 文章重写（相当于洗稿出来的结果，作为最终入库的依据）
 *
 * @generated from rpc sppb.MtmService.ArtRewrite
 */
export const artRewrite = MtmService.method.artRewrite;
