// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file mtm/sppb/mtm.proto (package sppb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  ArtContentClassifyReply,
  ArtContentClassifyReq,
  ArtRewriteReply,
  ArtRewriteReq,
  AuthToken,
  BlogCategorie,
  BlogCategorieCreateReply,
  BlogCategorieCreateReq,
  BlogCategorieGetReq,
  BlogCategorieListReply,
  BlogCategorieListReq,
  BlogCategorieUpdateReq,
  BlogCategorieUpdateReqply,
  BlogCleanReq,
  BlogPost,
  BlogPostCreateReq,
  BlogPostGetReq,
  BlogPostImportReq,
  BlogPostUpdateReq,
  CommontListReq,
  CommontListRes,
  Empty,
  FormCreateReq,
  FormGetReq,
  FormSchema,
  GetMetaReq,
  GetMetaRes,
  LoginReply,
  LoginReq,
  MtmServerListReq,
  MtmServerListRes,
  Oauth2LoginHookRequest,
  PullLogReq,
  PullLogRes,
  RegisterReply,
  RegisterReq,
  ResDeleteReq,
  Result,
  ServiceMetaReq,
  ServiceMetaRes,
  Site,
  SiteCreateReq,
  SiteCreateRes,
  SiteGetReq,
  SiteHost,
  SiteHostCreateReq,
  SiteHostGetReq,
  SiteHostListReply,
  SiteHostListReq,
  SiteHostUpdateReq,
  SiteImportReq,
  SiteSetupCftunnelReply,
  SiteSetupCftunnelReq,
  SiteUpdateReq,
  SlugReq,
  SlugRes,
  UserinfoRes,
} from "./mtm_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sppb.MtmService
 */
export const MtmService = {
  typeName: "sppb.MtmService",
  methods: {
    /**
     * @generated from rpc sppb.MtmService.Oauth2LoginHook
     */
    oauth2LoginHook: {
      name: "Oauth2LoginHook",
      I: Oauth2LoginHookRequest,
      O: AuthToken,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.Login
     */
    login: {
      name: "Login",
      I: LoginReq,
      O: LoginReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.Register
     */
    register: {
      name: "Register",
      I: RegisterReq,
      O: RegisterReply,
      kind: MethodKind.Unary,
    },
    /**
     * gomtm 基本元数据
     *
     * @generated from rpc sppb.MtmService.GetMeta
     */
    getMeta: {
      name: "GetMeta",
      I: GetMetaReq,
      O: GetMetaRes,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.PullLogs
     */
    pullLogs: {
      name: "PullLogs",
      I: PullLogReq,
      O: PullLogRes,
      kind: MethodKind.Unary,
    },
    /**
     * 获取可用服务器列表
     *
     * @generated from rpc sppb.MtmService.MtmServerList
     */
    mtmServerList: {
      name: "MtmServerList",
      I: MtmServerListReq,
      O: MtmServerListRes,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.ServiceMeta
     */
    serviceMeta: {
      name: "ServiceMeta",
      I: ServiceMetaReq,
      O: ServiceMetaRes,
      kind: MethodKind.Unary,
    },
    /**
     * 统一的列表查询接口
     *
     * @generated from rpc sppb.MtmService.Search
     */
    search: {
      name: "Search",
      I: CommontListReq,
      O: CommontListRes,
      kind: MethodKind.Unary,
    },
    /**
     * 动态页面
     *
     * @generated from rpc sppb.MtmService.SlugPage
     */
    slugPage: {
      name: "SlugPage",
      I: SlugReq,
      O: SlugRes,
      kind: MethodKind.Unary,
    },
    /**
     * 因为涉及到用户会话状态，所以用户登录上下文菜单独立定制
     *
     * @generated from rpc sppb.MtmService.Userinfo
     */
    userinfo: {
      name: "Userinfo",
      I: Empty,
      O: UserinfoRes,
      kind: MethodKind.Unary,
    },
    /**
     * blog-post
     *
     * @generated from rpc sppb.MtmService.BlogPostList
     */
    blogPostList: {
      name: "BlogPostList",
      I: CommontListReq,
      O: CommontListRes,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogPostGet
     */
    blogPostGet: {
      name: "BlogPostGet",
      I: BlogPostGetReq,
      O: BlogPost,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogPostCreate
     */
    blogPostCreate: {
      name: "BlogPostCreate",
      I: BlogPostCreateReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogPostUpdate
     */
    blogPostUpdate: {
      name: "BlogPostUpdate",
      I: BlogPostUpdateReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogPostDelete
     */
    blogPostDelete: {
      name: "BlogPostDelete",
      I: ResDeleteReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogPostImport
     */
    blogPostImport: {
      name: "BlogPostImport",
      I: BlogPostImportReq,
      O: BlogPost,
      kind: MethodKind.Unary,
    },
    /**
     * blog-categorie
     *
     * @generated from rpc sppb.MtmService.BlogCategorieList
     */
    blogCategorieList: {
      name: "BlogCategorieList",
      I: BlogCategorieListReq,
      O: BlogCategorieListReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogCategorieGet
     */
    blogCategorieGet: {
      name: "BlogCategorieGet",
      I: BlogCategorieGetReq,
      O: BlogCategorie,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogCategorieCreate
     */
    blogCategorieCreate: {
      name: "BlogCategorieCreate",
      I: BlogCategorieCreateReq,
      O: BlogCategorieCreateReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogCategorieUpdate
     */
    blogCategorieUpdate: {
      name: "BlogCategorieUpdate",
      I: BlogCategorieUpdateReq,
      O: BlogCategorieUpdateReqply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.BlogCategorieDelete
     */
    blogCategorieDelete: {
      name: "BlogCategorieDelete",
      I: ResDeleteReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * 清理重复内容
     *
     * @generated from rpc sppb.MtmService.BlogClean
     */
    blogClean: {
      name: "BlogClean",
      I: BlogCleanReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * Site
     *
     * @generated from rpc sppb.MtmService.SiteList
     */
    siteList: {
      name: "SiteList",
      I: CommontListReq,
      O: CommontListRes,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteGet
     */
    siteGet: {
      name: "SiteGet",
      I: SiteGetReq,
      O: Site,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteCreate
     */
    siteCreate: {
      name: "SiteCreate",
      I: SiteCreateReq,
      O: SiteCreateRes,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteUpdate
     */
    siteUpdate: {
      name: "SiteUpdate",
      I: SiteUpdateReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteDelete
     */
    siteDelete: {
      name: "SiteDelete",
      I: ResDeleteReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * 灵活创建spSite
     * 站点（自动提取目标域名，自动创建相关配置，确保导入后能立即生效）
     *
     * @generated from rpc sppb.MtmService.SiteImport
     */
    siteImport: {
      name: "SiteImport",
      I: SiteImportReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteSetupCftunnel
     */
    siteSetupCftunnel: {
      name: "SiteSetupCftunnel",
      I: SiteSetupCftunnelReq,
      O: SiteSetupCftunnelReply,
      kind: MethodKind.Unary,
    },
    /**
     * 站点域名配置
     *
     * @generated from rpc sppb.MtmService.SiteHostList
     */
    siteHostList: {
      name: "SiteHostList",
      I: SiteHostListReq,
      O: SiteHostListReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteHostGet
     */
    siteHostGet: {
      name: "SiteHostGet",
      I: SiteHostGetReq,
      O: SiteHost,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteHostCreate
     */
    siteHostCreate: {
      name: "SiteHostCreate",
      I: SiteHostCreateReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteHostUpdate
     */
    siteHostUpdate: {
      name: "SiteHostUpdate",
      I: SiteHostUpdateReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.SiteHostDelete
     */
    siteHostDelete: {
      name: "SiteHostDelete",
      I: ResDeleteReq,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.FormList
     */
    formList: {
      name: "FormList",
      I: CommontListReq,
      O: CommontListRes,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.FormGet
     */
    formGet: {
      name: "FormGet",
      I: FormGetReq,
      O: FormSchema,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sppb.MtmService.FormCreate
     */
    formCreate: {
      name: "FormCreate",
      I: FormCreateReq,
      O: FormSchema,
      kind: MethodKind.Unary,
    },
    /**
     * 文本内容分类(过时，因为文章分类不会直接调用)
     *
     * @generated from rpc sppb.MtmService.ArtContentClassify
     */
    artContentClassify: {
      name: "ArtContentClassify",
      I: ArtContentClassifyReq,
      O: ArtContentClassifyReply,
      kind: MethodKind.Unary,
    },
    /**
     * 文章重写（相当于洗稿出来的结果，作为最终入库的依据）
     *
     * @generated from rpc sppb.MtmService.ArtRewrite
     */
    artRewrite: {
      name: "ArtRewrite",
      I: ArtRewriteReq,
      O: ArtRewriteReply,
      kind: MethodKind.Unary,
    },
  },
} as const;
