version: "3.9"
networks:
  net:
    name: mtmht-net
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default

volumes:
  pgdb:
    name: pgdb_ht
  mysqldb:
    name: mysqldb6
  workspace:
    name: workspace
  redis_data:
    name: redis_data
  grafana_storage:
    name: grafana_storage
  pgdb_data:
    name: pgdb1
  appStorage:
    name: appStorage

x-networks: &network
  networks:
    - net

services:
  # docker-compose up pgdb
  pgdb:
    image: postgres:16
    container_name: pgdb
    restart: unless-stopped
    <<: *network
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    deploy:
      resources:
        limits:
          memory: 1024M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"
    volumes:
      # 持久数据
      - pgdb_data:/var/lib/postgresql/data:Z