// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file api-contracts/events/events.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  BulkPushEventRequest,
  Event,
  Events,
  PushEventRequest,
  PutLogRequest,
  PutLogResponse,
  PutStreamEventRequest,
  PutStreamEventResponse,
  ReplayEventRequest,
} from "./events_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service EventsService
 */
export const EventsService = {
  typeName: "EventsService",
  methods: {
    /**
     * @generated from rpc EventsService.Push
     */
    push: {
      name: "Push",
      I: PushEventRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc EventsService.BulkPush
     */
    bulkPush: {
      name: "BulkPush",
      I: BulkPushEventRequest,
      O: Events,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc EventsService.ReplaySingleEvent
     */
    replaySingleEvent: {
      name: "ReplaySingleEvent",
      I: ReplayEventRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc EventsService.PutLog
     */
    putLog: {
      name: "PutLog",
      I: PutLogRequest,
      O: PutLogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc EventsService.PutStreamEvent
     */
    putStreamEvent: {
      name: "PutStreamEvent",
      I: PutStreamEventRequest,
      O: PutStreamEventResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
