/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutsrootImport } from './routes/layouts/__root'
import { Route as PostsImport } from './routes/posts'
import { Route as AnchorImport } from './routes/anchor'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as WorkflowsIndexImport } from './routes/workflows/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as DashIndexImport } from './routes/dash/index'
import { Route as WorkflowsWorkflowIdImport } from './routes/workflows/$workflowId'
import { Route as PostsPostIdImport } from './routes/posts/$postId'
import { Route as LayoutsLayout2LayoutBImport } from './routes/layouts/_layout-2/layout-b'
import { Route as LayoutsLayout2LayoutAImport } from './routes/layouts/_layout-2/layout-a'

// Create Virtual Routes

const LayoutsImport = createFileRoute('/layouts')()

// Create/Update Routes

const LayoutsrootRoute = LayoutsrootImport.update({
  id: '/__root',
  getParentRoute: () => LayoutsRoute,
} as any)

const LayoutsRoute = LayoutsImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => rootRoute,
} as any)

const PostsRoute = PostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const AnchorRoute = AnchorImport.update({
  id: '/anchor',
  path: '/anchor',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowsIndexRoute = WorkflowsIndexImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)

const DashIndexRoute = DashIndexImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)

const LayoutsLayout2LayoutBRoute = LayoutsLayout2LayoutBImport.update({
  id: '/_layout-2/layout-b',
  path: '/layout-b',
  getParentRoute: () => LayoutsRoute,
} as any)

const LayoutsLayout2LayoutARoute = LayoutsLayout2LayoutAImport.update({
  id: '/_layout-2/layout-a',
  path: '/layout-a',
  getParentRoute: () => LayoutsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/anchor': {
      id: '/anchor'
      path: '/anchor'
      fullPath: '/anchor'
      preLoaderRoute: typeof AnchorImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/layouts': {
      id: '/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof LayoutsImport
      parentRoute: typeof rootRoute
    }
    '/layouts/__root': {
      id: '/layouts/__root'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof LayoutsrootImport
      parentRoute: typeof LayoutsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof PostsImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdImport
      parentRoute: typeof rootRoute
    }
    '/dash/': {
      id: '/dash/'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof PostsImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsIndexImport
      parentRoute: typeof rootRoute
    }
    '/layouts/_layout-2/layout-a': {
      id: '/layouts/_layout-2/layout-a'
      path: '/layout-a'
      fullPath: '/layouts/layout-a'
      preLoaderRoute: typeof LayoutsLayout2LayoutAImport
      parentRoute: typeof LayoutsImport
    }
    '/layouts/_layout-2/layout-b': {
      id: '/layouts/_layout-2/layout-b'
      path: '/layout-b'
      fullPath: '/layouts/layout-b'
      preLoaderRoute: typeof LayoutsLayout2LayoutBImport
      parentRoute: typeof LayoutsImport
    }
  }
}

// Create and export the route tree

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface LayoutsRouteChildren {
  LayoutsrootRoute: typeof LayoutsrootRoute
  LayoutsLayout2LayoutARoute: typeof LayoutsLayout2LayoutARoute
  LayoutsLayout2LayoutBRoute: typeof LayoutsLayout2LayoutBRoute
}

const LayoutsRouteChildren: LayoutsRouteChildren = {
  LayoutsrootRoute: LayoutsrootRoute,
  LayoutsLayout2LayoutARoute: LayoutsLayout2LayoutARoute,
  LayoutsLayout2LayoutBRoute: LayoutsLayout2LayoutBRoute,
}

const LayoutsRouteWithChildren =
  LayoutsRoute._addFileChildren(LayoutsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/anchor': typeof AnchorRoute
  '/posts': typeof PostsRouteWithChildren
  '/layouts': typeof LayoutsrootRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/dash': typeof DashIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/layouts/layout-a': typeof LayoutsLayout2LayoutARoute
  '/layouts/layout-b': typeof LayoutsLayout2LayoutBRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/anchor': typeof AnchorRoute
  '/layouts': typeof LayoutsrootRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/dash': typeof DashIndexRoute
  '/posts': typeof PostsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/layouts/layout-a': typeof LayoutsLayout2LayoutARoute
  '/layouts/layout-b': typeof LayoutsLayout2LayoutBRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/anchor': typeof AnchorRoute
  '/posts': typeof PostsRouteWithChildren
  '/layouts': typeof LayoutsRouteWithChildren
  '/layouts/__root': typeof LayoutsrootRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/dash/': typeof DashIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/layouts/_layout-2/layout-a': typeof LayoutsLayout2LayoutARoute
  '/layouts/_layout-2/layout-b': typeof LayoutsLayout2LayoutBRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/anchor'
    | '/posts'
    | '/layouts'
    | '/posts/$postId'
    | '/workflows/$workflowId'
    | '/dash'
    | '/posts/'
    | '/workflows'
    | '/layouts/layout-a'
    | '/layouts/layout-b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/anchor'
    | '/layouts'
    | '/posts/$postId'
    | '/workflows/$workflowId'
    | '/dash'
    | '/posts'
    | '/workflows'
    | '/layouts/layout-a'
    | '/layouts/layout-b'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/anchor'
    | '/posts'
    | '/layouts'
    | '/layouts/__root'
    | '/posts/$postId'
    | '/workflows/$workflowId'
    | '/dash/'
    | '/posts/'
    | '/workflows/'
    | '/layouts/_layout-2/layout-a'
    | '/layouts/_layout-2/layout-b'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  AnchorRoute: typeof AnchorRoute
  PostsRoute: typeof PostsRouteWithChildren
  LayoutsRoute: typeof LayoutsRouteWithChildren
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  DashIndexRoute: typeof DashIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  AnchorRoute: AnchorRoute,
  PostsRoute: PostsRouteWithChildren,
  LayoutsRoute: LayoutsRouteWithChildren,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  DashIndexRoute: DashIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/anchor",
        "/posts",
        "/layouts",
        "/workflows/$workflowId",
        "/dash/",
        "/workflows/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/anchor": {
      "filePath": "anchor.tsx"
    },
    "/posts": {
      "filePath": "posts.tsx",
      "children": [
        "/posts/$postId",
        "/posts/"
      ]
    },
    "/layouts": {
      "filePath": "layouts",
      "children": [
        "/layouts/__root",
        "/layouts/_layout-2/layout-a",
        "/layouts/_layout-2/layout-b"
      ]
    },
    "/layouts/__root": {
      "filePath": "layouts/__root.tsx",
      "parent": "/layouts"
    },
    "/posts/$postId": {
      "filePath": "posts/$postId.tsx",
      "parent": "/posts"
    },
    "/workflows/$workflowId": {
      "filePath": "workflows/$workflowId.tsx"
    },
    "/dash/": {
      "filePath": "dash/index.tsx"
    },
    "/posts/": {
      "filePath": "posts/index.tsx",
      "parent": "/posts"
    },
    "/workflows/": {
      "filePath": "workflows/index.tsx"
    },
    "/layouts/_layout-2/layout-a": {
      "filePath": "layouts/_layout-2/layout-a.tsx",
      "parent": "/layouts"
    },
    "/layouts/_layout-2/layout-b": {
      "filePath": "layouts/_layout-2/layout-b.tsx",
      "parent": "/layouts"
    }
  }
}
ROUTE_MANIFEST_END */
