name: build

on:
  workflow_dispatch:
    inputs:
      input:
        description: '功能选项 (1: 仅构建, 2: 构建并部署, 3: 构建docker镜像并发布)'
        required: true
        type: choice
        options:
          - '1'
          - '2'
          - '3'
        default: '1'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install
      # - uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: latest

      # - name: bun install
      #   run: bun install --development

      - name: bun build
        run: bun run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: patch version
      #   run: |
      #     npm version patch
      #     git add package.json
      #     git commit -m "patch version"
      #     git push

