// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file mtmai/mtm/cli.proto (package mtmai.mtm.sppb, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mtmai/mtm/cli.proto.
 */
export const file_mtmai_mtm_cli: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChNtdG1haS9tdG0vY2xpLnByb3RvEg5tdG1haS5tdG0uc3BwYiI8Cg5DbGlDb21tYW5kSXRlbRIKCgJpZBgBIAEoCRIPCgdjbWRMaW5lGAIgASgJEg0KBWxhYmVsGAMgASgJIgwKCkxpc3RDbGlSZXEiSgoKTGlzdENsaVJlcxItCgVpdGVtcxgBIAMoCzIeLm10bWFpLm10bS5zcHBiLkNsaUNvbW1hbmRJdGVtEg0KBWNvdW50GAIgASgNMl8KDE10Q2xpU2VydmljZRJPChNDbGlDb21tYW5kVGVtcGxhdGVzEhoubXRtYWkubXRtLnNwcGIuTGlzdENsaVJlcRoaLm10bWFpLm10bS5zcHBiLkxpc3RDbGlSZXMiAEKhAQoSY29tLm10bWFpLm10bS5zcHBiQghDbGlQcm90b1ABWidnaXRodWIuY29tL2NvZGVoMDA3L2dvbXRtL210bS9zcHBiO3NwcGKiAgNNTVOqAg5NdG1haS5NdG0uU3BwYsoCDk10bWFpXE10bVxTcHBi4gIaTXRtYWlcTXRtXFNwcGJcR1BCTWV0YWRhdGHqAhBNdG1haTo6TXRtOjpTcHBiYgZwcm90bzM",
  );

/**
 * @generated from message mtmai.mtm.sppb.CliCommandItem
 */
export type CliCommandItem = Message<"mtmai.mtm.sppb.CliCommandItem"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string cmdLine = 2;
   */
  cmdLine: string;

  /**
   * @generated from field: string label = 3;
   */
  label: string;
};

/**
 * Describes the message mtmai.mtm.sppb.CliCommandItem.
 * Use `create(CliCommandItemSchema)` to create a new message.
 */
export const CliCommandItemSchema: GenMessage<CliCommandItem> =
  /*@__PURE__*/
  messageDesc(file_mtmai_mtm_cli, 0);

/**
 * @generated from message mtmai.mtm.sppb.ListCliReq
 */
export type ListCliReq = Message<"mtmai.mtm.sppb.ListCliReq"> & {};

/**
 * Describes the message mtmai.mtm.sppb.ListCliReq.
 * Use `create(ListCliReqSchema)` to create a new message.
 */
export const ListCliReqSchema: GenMessage<ListCliReq> =
  /*@__PURE__*/
  messageDesc(file_mtmai_mtm_cli, 1);

/**
 * @generated from message mtmai.mtm.sppb.ListCliRes
 */
export type ListCliRes = Message<"mtmai.mtm.sppb.ListCliRes"> & {
  /**
   * @generated from field: repeated mtmai.mtm.sppb.CliCommandItem items = 1;
   */
  items: CliCommandItem[];

  /**
   * @generated from field: uint32 count = 2;
   */
  count: number;
};

/**
 * Describes the message mtmai.mtm.sppb.ListCliRes.
 * Use `create(ListCliResSchema)` to create a new message.
 */
export const ListCliResSchema: GenMessage<ListCliRes> =
  /*@__PURE__*/
  messageDesc(file_mtmai_mtm_cli, 2);

/**
 * @generated from service mtmai.mtm.sppb.MtCliService
 */
export const MtCliService: GenService<{
  /**
   * @generated from rpc mtmai.mtm.sppb.MtCliService.CliCommandTemplates
   */
  cliCommandTemplates: {
    methodKind: "unary";
    input: typeof ListCliReqSchema;
    output: typeof ListCliResSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_mtmai_mtm_cli, 0);
