name: build

on:
  workflow_dispatch:
    inputs:
      input:
        description: '功能选项 (1: 仅构建, 2: 构建并部署, 3: 构建docker镜像并发布)'
        required: true
        type: choice
        options:
          - '1'
          - '2'
          - '3'
        default: '1'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug_info:
    needs: main_route
    if: needs.main_route.outputs.nextjob != 'none'
    runs-on: ubuntu-latest
    steps:
      - name: Show routing info
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Next job to run: ${{ needs.main_route.outputs.nextjob }}"

      - name: Show commit info
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Commit author: ${{ github.event.head_commit.author.name }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Show GitHub context
        run: echo "${{ toJSON(github) }}"

      - name: Show environment variables
        run: env

  build:
    needs: main_route
    if: needs.main_route.outputs.nextjob == 'build_gomtm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: bun install
        run: bun install
      - name: bun build
        run: bun run build