name: deploy

on:
  push:
    paths:
      - "packages/**"
      - "apps/**"
      - "package.json"
    branches:
      - main
  workflow_dispatch:
    inputs:
      input:
        description: "功能选项 (1: 仅构建, 2: 构建并部署, 3: 构建docker镜像并发布)"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
        default: "1"

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MTM_DATABASE_URL: ${{ secrets.MTM_DATABASE_URL }}
  SERVER_MSGQUEUE_RABBITMQ_URL: ${{ secrets.SERVER_MSGQUEUE_RABBITMQ_URL }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
  CLOUDFLARE_AI_TOKEN: ${{ secrets.CLOUDFLARE_AI_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  GOPRIVATE: ${{ secrets.GOPRIVATE }}

  # Tag Image with tag name on release
  # else with user specified tag (default 'dev') if triggered via workflow
  # else with run_id if triggered via a pull request
  # else with 'pre' (if push to master)
  DOCKER_IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.event_name == 'workflow_dispatch' && github.event.inputs.tag || 'pre' }}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.SAGE_PAT }}

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: bun run build

      - name: chmod
        run: |
          chmod 777 -R packages/gomtm-cli/bin/*

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用 PAT 替代默认的 GITHUB_TOKEN
          # GITHUB_TOKEN: ${{ secrets.SAGE_PAT }}

      # - name: Slack notification
      #   if: steps.changesets.outputs.published == 'true'
      #   run: pnpm slack
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  deploy:
    needs: [release]
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup bun
        uses: ./.github/actions/setup_bun

      - name: install gomtm
        run: |
          cd packages/gomtm-cli
          npm i -g

      - name: deploy mtmaiui cfpage
        run: |
          (cd apps/mtmaiui && bun run build && gomtm cfpage)

  deploy_vercel:
    needs: [deploy]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup bun
        uses: ./.github/actions/setup_bun

      - name: install gomtm
        run: |
          cd packages/gomtm-cli
          npm i -g

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
          check-latest: true
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"

      - name: deploy to vercel
        run: |
          cd apps/mtmaiui
          gomtm vc


  build_docker_gomtm_base:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建基础gomtmdocker镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/gomtmbase:latest
          file: packages/gomtm-cli/Dockerfile
          target: mtmbase

      - name: 构建gomtm-cli docker镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/gomtm:latest
          file: packages/gomtm-cli/Dockerfile
          target: gomtm

