name: dp_cfpage

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
      - "apps/**"
      - "package.json"
    branches:
      - main
  workflow_dispatch:
    inputs:
      input:
        description: "功能选项 (1: 仅构建, 2: 构建并部署, 3: 构建docker镜像并发布)"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
        default: "1"

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  MTM_DATABASE_URL: ${{ secrets.MTM_DATABASE_URL }}

jobs:
  dp_cfpage:
    name: dp_cfpage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.SAGE_PAT }}
      - name: setup bun
        uses: ./.github/actions/setup_bun

      - name: 使用gomtm 进行 cfpage 部署
        run: (cd apps/testui && ../../packages/gomtm-cli/bin/gomtm dp cfpage)
