name: dp_cfpage

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
      - "apps/**"
      - "package.json"
    branches:
      - main
  workflow_dispatch:
    inputs:
      input:
        description: "功能选项 (1: 仅构建, 2: 构建并部署, 3: 构建docker镜像并发布)"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
        default: "1"

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write
  # workflows: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MTM_DATABASE_URL: ${{ secrets.MTM_DATABASE_URL }}
  SERVER_MSGQUEUE_RABBITMQ_URL: ${{ secrets.SERVER_MSGQUEUE_RABBITMQ_URL }}

jobs:
  dp_cfpage:
    name: dp_cfpage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.SAGE_PAT }}

      - name: setup bun
        uses: ./.github/actions/setup_bun

      - name: 测试gomtm 命令
        run: (cd apps/testui && ../../packages/gomtm-cli/bin/gomtm dp --help)

      - name: 使用gomtm 进行 cfpage 部署
        run: (cd apps/testui && ../../packages/gomtm-cli/bin/gomtm dp cfpage)

  testing_gomtm_worker:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [dp_cfpage]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.SAGE_PAT }}

      - name: 测试是否能自动启动worker
        run: (cd apps/testui && ../../packages/gomtm-cli/bin/gomtm)
