name: dp_cfpage_mtmaiui

on:
  push:
    paths:
      - "packages/mtmaiui/**/*"
      - "packages/mtmaiapi/**/*"
      - "packages/mtxuilib/**/*"
      - "package.json"
    branches:
      - main
  workflow_dispatch:
    inputs:
      input:
        description: "功能选项 (1: 仅构建, 2: 构建并部署, 3: 构建docker镜像并发布)"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
        default: "1"

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MTM_DATABASE_URL: ${{ secrets.MTM_DATABASE_URL }}
  SERVER_MSGQUEUE_RABBITMQ_URL: ${{ secrets.SERVER_MSGQUEUE_RABBITMQ_URL }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
  CLOUDFLARE_AI_TOKEN: ${{ secrets.CLOUDFLARE_AI_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  dp_mtmaiui:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup bun
        uses: ./.github/actions/setup_bun

      - name: deploy to cloudflare pages
        run: (cd packages/mtmaiui && bun run build && ../../packages/gomtm-cli/bin/gomtm dp cfpage)
