name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
      - "apps/**"
      - "package.json"
    branches:
      - main
  workflow_dispatch:
    inputs:
      input:
        description: "功能选项 (1: 仅构建, 2: 构建并部署, 3: 构建docker镜像并发布)"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
        default: "1"

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # tests:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v4

  #     - name: Install
  #       uses: ./.github/composite-actions/install

  #     - name: Run tests
  #       run: pnpm test

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.SAGE_PAT }}

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: bun run build

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用 PAT 替代默认的 GITHUB_TOKEN
          # GITHUB_TOKEN: ${{ secrets.SAGE_PAT }}

      # - name: Slack notification
      #   if: steps.changesets.outputs.published == 'true'
      #   run: pnpm slack
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
